### ISSUE TITLE
Would it be possible to include data preparation code?

### ISSUE THREAD

**Issue by cmhh** [zhenhua-wang/MissingData_DL#1]
Hi

I read the corresponding paper on arxiv and I was going to try running the code, but it wasn't obvious how to produce `data/house.csv`.  I downloaded `https://www2.census.gov/programs-surveys/acs/data/pums/2019/1-Year/csv_hus.zip`, but that obviously needs a fair bit of treatment to be turned into something consistent with your code?  I wonder if it might be possible to include the code that does this preprocessing?

As a minor aside, I found the `utils/utils.py` script had a few indentation issues that stopped the code running for me.  Mostly just the docstrings, I think.

**Comment by zhenhua-wang** [comment]
Thanks for letting me know. I've uploaded the codes for data preprocessing to the folder "R". It contains a downloader and a script for preprocessing. **I also add a link in README.md to the processed data in google drive**

Note: 
- I didn't let it generate folder automatically, so you need to create a folder "2018" in the data folder. 
- You may need a computer with large RAM to run this script, since the raw data is huge

Indeed the docstring has some indentation issues. I'll fix it.

**Comment by cmhh** [comment]
Sorry.  Forgot to say thanks.  I've cloned the new stuff but haven't tried running it yet.  Thanks again!

**Comment by zhenhua-wang** [comment]
No problem. let me know if there are any other issues!
